### ISSUE TITLE
Possible Bugs, Loader.py not working? 

### ISSUE THREAD

**Issue by SinghJasdeep** [markdtw/vqa-winner-cvprw-2017#4]
Hello we are using you code to preprocess the data and build a few models on top of and are running into some bugs. Don't know why this is not working for us. 

https://github.com/SinghJasdeep/CS230-CS224N-VQA

Mainly issues in the loader.py file:

i_batch.append(self.i_feat[iid]) is actually a dictionary not an array of size (36,2048)?

Your help would be greatly appreciated Mark.

**Comment by SinghJasdeep** [comment]
I think the error is possibly how we are saving coco_features.npy

Could you please post the version of read_tsv.py you use. 

We are using this:

import base64
import numpy as np
import csv
import sys
import zlib
import time
import mmap

csv.field_size_limit(sys.maxsize)

FIELDNAMES = ['image_id', 'image_w', 'image_h', 'num_boxes', 'boxes', 'features']
infile = '/home/vhying/Downloads/CS230-CS224N-VQA/data/trainval_36/trainval_resnet101_faster_rcnn_genome_36.tsv'
outfile = '/home/vhying/Downloads/CS230-CS224N-VQA/data/coco_features.npy'

if __name__ == '__main__':

    # Verify we can read a tsv
    in_data = {}
    with open(infile, "r+b") as tsv_in_file:
        reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames=FIELDNAMES)
        for item in reader:
            item['image_id'] = int(item['image_id'])
            item['image_h'] = int(item['image_h'])
            item['image_w'] = int(item['image_w'])
            item['num_boxes'] = int(item['num_boxes'])
            for field in ['boxes', 'features']:
                item[field] = np.frombuffer(base64.decodestring(item[field]),
                                            dtype=np.float32).reshape((item['num_boxes'], -1))
            in_data[item['image_id']] = item

        with open(outfile, "wb") as Out_f:
            np.save(outfile, in_data)

**Comment by SinghJasdeep** [comment]
Issue Solved

**Comment by kevgeo** [comment]
Hi @SinghJasdeep , even I am facing a similar problem. How did you resolve the issue? Could you share your version of  read_tsv.py? That would be great.

**Comment by markdtw** [comment]
Hi, sorry I really should've put my read_tsv.py here

it's like this

```python
...
    in_data = {}
...
        for item in reader:
            data = {}
            data['image_id'] = int(item['image_id'])
            for field in ['features']:
                data[field] = np.frombuffer(base64.decodestring(item[field]),
                    dtype=np.float32).reshape((36, -1))
            in_data[data['image_id']] = data['features']

        np.save('purefeat.npy', in_data)
...
```

**Comment by kevgeo** [comment]
@markdtw Thank you so much for the code :).
